[package]
name = "xbps-updater"
version = "0.1.0"
authors = ["Coding-Doctors <hoffmeyer25@gmail.com>"]

[dependencies]
hubcaps = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
failure = "0.1"
failure_derive = "0.1"
