[package]
name = "xbps-updater"
version = "0.1.0"
authors = ["Coding-Doctors <hoffmeyer25@gmail.com>"]

[dependencies]
github-rs = { version = "0.6", path = "../../git/github-rs" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
